default_language_version:
  python: python3
exclude: "^src/atomate2/vasp/schemas/calc_types/"
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.284
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: fix-encoding-pragma
        args: [--remove]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.15.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]
        exclude: README.md
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        entry: pflake8
        files: ^src/
        additional_dependencies:
          - pyproject-flake8
          - flake8-bugbear
          - flake8-typing-imports
          - flake8-docstrings
          - flake8-rst-docstrings
          - flake8-rst
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        files: ^src/
        additional_dependencies:
          - tokenize-rt
          - types-pkg_resources
          - types-paramiko
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        stages: [commit, commit-msg]
        args: [--ignore-words-list, "titel,statics,ba,nd,te"]
        types_or: [python, rst, markdown]
